base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('index/', views.index, name='index'),
]

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('userprofile.urls')),
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('store.urls')),
    
    
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('change_quantity/<str:product_id>/', views.change_quantity, name='change_quantity'),
    path('remove_from_cart/<str:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

userprofile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('my_store_order_detail/<int:pk>/', views.my_store_order_detail, name='my_store_order_detail'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('my_store/', views.my_store, name='my_store'),
    path('my_store/add_product/', views.add_product, name='add_product'),
    path('my-store/edit_product/<int:pk>/', views.edit_product, name='edit_product'),
    path('my_store/delete_product/<int:pk>/', views.delete_product, name='delete_product'),
    path('vendors/<int:pk>/', views.vendor_detail, name='vendor_detail'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.files import File 
from io import BytesIO
from PIL import Image


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.title
    
class Product(models.Model):

    DRAFT = 'draft'
    WAITING_APPROVAL = 'waitingapproval'
    ACTIVE = 'active'
    DELETED = 'deleted'

    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )


    user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='uploads/product_images', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/product_images/thumbnail', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices= STATUS_CHOICES, default=ACTIVE)

    class Meta:
        ordering =['-created_at']

    def __str__(self) -> str:
        return self.title
    
    def get_display_price(self):
        return self.price / 100
    

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/240x240x.jpg'
    
    def make_thumbnail(self, image, size=(300, 300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)
        name = image.name.replace('uploads/product_images', '' )
        thumbnail = File(thumb_io, name=name)

        return thumbnail
    

class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.first_name


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def get_display_price(self):
        return self.price / 100

    def __str__(self) -> str:
        return self.product

store/forms.py
from django import forms

from . models import Product, Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'address', 'zipcode', 'city',)

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'title', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': 'w-full p-4 border border-blue-700 rounded-xl'
            }),
            'title': forms.TextInput(attrs={
                'class': 'w-full p-4 border border-blue-200 rounded-xl'
            }),
            'description': forms.Textarea(attrs={
                'class': 'w-full p-4 border-blue-200 rounded-xl'
            }),
            'price': forms.TextInput(attrs={
                'class': 'w-full p-4 border-blue-700 rounded-xl'
            }),
            'image': forms.FileInput(attrs={
                'class': 'w-full p-4 border border-blue-700 rounded-xl'
            }),
        }

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .cart import Cart
from .forms import OrderForm
from .models import Product, Category, Order, OrderItem


def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)
    return redirect('store:cart_view')

def change_quantity(request, product_id):
    action = request.GET.get('action', '')

    if action:
        quantity = 1

        if action == 'decrease':
            quantity = -1
        
        cart = Cart(request)
        cart.add(product_id, quantity, True)

    return redirect('store:cart_view')

def remove_from_cart(request, product_id):
    cart = Cart(request)
    cart.remove (product_id)

    return redirect('store:cart_view')


def cart_view(request):
    cart = Cart(request)

    return render(request, template_name='store/cart_view.html', context={'cart': cart})


@login_required
def checkout(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            total_price = 0


            for item in cart:
                product = item['product']
                total_price += product.price * int(item['quantity'])


            order = form.save(commit=False)
            order.created_by = request.user
            order.paid_amount = total_price
            order.save()


            for item in cart:
                product = item['product']
                quantity = int(item['quantity'])
                price = product.price * quantity

                item = OrderItem.objects.create(order=order, product=product, price=price, quantity=quantity)
            
            cart.clear()
     
            return redirect('userprofile:myaccount') #this should go to JsonResponse instead

    else:
        form = OrderForm()

    return render(request, 'store/checkout.html', {
        'cart': cart,
        'form': form,
    })


def search(request):
    query = request.GET.get('query', '')
    products = Product.objects.filter(status= Product.ACTIVE).filter(Q(title__icontains=query) | Q(description__icontains=query))

    return render(request, template_name='store/search.html', context={'query': query, 'products': products})

def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Category.products.filter(status= Product.ACTIVE)
    return render(request, template_name='store/category_detail.html', context={'category': category, 'products':products})

def product_detail(request, category_slug, slug):
    product = get_object_or_404(Product, slug=slug, status=Product.ACTIVE)
    return render(request, template_name='store/product_detail.html', context={'product': product})

store/templates/store/cart_view.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
    <h1 class="text-2xl mb-4 text-green-500">Cart</h1>

    <hr>

          
    {% if cart|length %}
    
            {% for item in cart %}
            <div class="py-6 px-6 mt-2 bg-blue-100 flex items-center">
                <div>
                    <img src="{{ item.product.get_thumbnail }}" class="w-20">
                </div>

                <div class="pl-6">
                    <h2 class="text-2xl">{{ item.product.title }}</h2>

                    <p class="text-sm text-blue-500">${{ item.product.get_display_price }}</p>

                <div class="mt-4 mb-4">
                    <a href="{% url 'store:change_quantity' item.product.id %}?action=increase" class="p-2 rounded-xl bg-blue-500 text-white">+</a>
                    {{ item.quantity }}
                    <a href="{% url 'store:change_quantity' item.product.id %}?action=decrease" class="p-2 rounded-xl bg-blue-500 text-white">-</a>
                </div>

                <a href="{% url 'store:remove_from_cart' item.product.id %}" class="inline-block"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                   </svg>
                  </a>
                </div>     
            </div>
          {% endfor %}

    <hr class="mb-4 mt-4">
    <strong>Total Cost: </strong>${{ cart.get_total_cost }}

    <hr class="mt-4 mb-4">
    
    <a href="{% url 'store:checkout' %}" class="inline-block px-8 py-4 bg-blue-500 text-white rounded-xl">Checkout</a>
    
    {% else %}
        <div class="px-6 py-6 bg-blue-300">
            Nothing is in your cart yet, add now
        </div>
    {% endif %}
{% endblock %}

store/templates/store/category_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    <h1 class="text-2xl">{{ category.title }}</h1>

    {% include 'store/partials/products.html' %}
{% endblock %}

store/templates/store/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
    <h1 class="text-2xl mb-4 text-green-500">Checkout</h1>


    <h2 class="text-xl text-blue-500">Total Cost: ${{ cart.get_total_cost }}</h2>

<form method="post" action=".">
    {% csrf_token %}

    {{ form.as_p}}
    <button class="inline-block px-8 py-4 bg-blue-500 text-white rounded-xl">Checkout</button>
</form>
{% endblock %}

store/templates/store/product_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}

{% if product.image %}   
<div class="image mb-4">
    <img src="{{ product.image.url }}" alt="Image of {{ product.title }}">

</div>
{% endif %}
    <h1 class="2xl">{{ product.title }}</h1>

    <p class="text-xs text-gray-500">
        
        ${{ product.get_display_price }}
         -
        <a href="{% url 'userprofile:vendor_detail' product.user.id %}">{% firstof product.user.get_full_name product.user.username %}</a>
    </p>

    
        {% if product.description %}
             <p class="text-sm mt-4">
                {{ product.description }}
            </p>
        {% endif %}

        <a href="{% url 'store:add_to_cart' product.id %}" class="mt-4 inline-block px-8 py-4 bg-teal-500 text-white rounded-xl">Add to Cart</a>

{% endblock %}

store/templates/store/search.html
{% extends 'core/base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1 class="text-2xl text-green-500">Search</h1>

    <h2 class="text-xs text-gray-600">Search results for "{{ query }}":</h2>
    {% if products %}
        {% include 'store/partials/products.html' %}
    {% else %}
        <p>No products Available</p>
    {% endif %}
{% endblock %}