base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('index/', views.index, name='index'),
]

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('userprofile.urls')),
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('store.urls')),
    
    
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('change_quantity/<str:product_id>/', views.change_quantity, name='change_quantity'),
    path('remove_from_cart/<str:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

userprofile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('my_store_order_detail/<int:pk>/', views.my_store_order_detail, name='my_store_order_detail'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('my_store/', views.my_store, name='my_store'),
    path('my_store/add_product/', views.add_product, name='add_product'),
    path('my-store/edit_product/<int:pk>/', views.edit_product, name='edit_product'),
    path('my_store/delete_product/<int:pk>/', views.delete_product, name='delete_product'),
    path('vendors/<int:pk>/', views.vendor_detail, name='vendor_detail'),
]

base/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request,'base/index.html')

core/views.py
from django.shortcuts import render

from store.models import Product

def frontpage(request):
    products = Product.objects.filter(status=Product.ACTIVE)[0:9]
    return render(request, template_name='core/frontpage.html', context={'products': products})

core/templates/core/base.html
{% load menu %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Zago Mart</title>
</head>
<body>

    <nav class="py-6 px-6 flex items-center justify-between bg-blue-900">
        <a href="/" class="text-green-300 font-semibold">Zago Mart</a>

        <div class="search">
            <form method="get" action="/search/" class="flex items-center space-x-3">
                <input type="search" name="query" placeholder="Search.." class="py-2 px-4 rounded-xl">
                <button><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 15.75l-2.489-2.489m0 0a3.375 3.375 0 10-4.773-4.773 3.375 3.375 0 004.774 4.774zM21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  </button>
            </form>
        </div>

        <div class="menu flex space-x-4 items-center">
            {% menu %}
            

            <a href="{% url 'store:cart_view' %}" class="text-white bg-blue-600 flex space-x-2 hover:text-blue-500 py-2 px-4 rounded-xl"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
              </svg> <span>({{ cart|length }})</span>
            </a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'userprofile:myaccount' %}"class="text-white bg-blue-600 hover:text-cyan-500 py-2 px-4 rounded-xl">My Account</a>
                
                {% if request.user.userprofile.is_vendor %}
                    <a href="{% url 'userprofile:my_store' %}" class="text-white bg-blue-600 py-2 px-4 rounded-xl">My Store</a>
                {% endif %}
            {% else %}
           <a href="{% url 'userprofile:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
            <a href="{% url 'userprofile:login' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Log In</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
        
    
    <footer class="py-6 px-6 flex justify-between bg-blue-900">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">This the the about page, where you make purchases with ease
            </p>
        </div>
        
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Frontpage{% endblock %}

{% block content %}
    {% include 'store/partials/products.html' %}
{% endblock %}

core/templates/core/menu.html
{% for category in categories %}
    <a href="{% url 'store:category_detail' category.slug %}" class="text-blue-500 mx-auto hover:text-teal-500">{{ category.title }}</a>
{% endfor %}